"""
PIP installations before beiginning:
1. pip install google-genai (Since October/November 2024)
2. pip install google-generativeai (Older version of google-genai, not recommended). It was part of Commit 1 & 2
The installations come from Python Package Index (PyPI) and pip tool delivers the package to the system.
"""
import os
from google import genai
from google.genai import types

#Configuring API key
"""
The client gets the API key from the environment variable `GEMINI_API_KEY`.
However we are using variable name `aistudio_key_laboratory` to store the API key, 
so we need to pass it to the client. This is because the client is looking for the environment variable `GEMINI_API_KEY` by default, but we are using a different variable name to store the API key. 
By passing the API key. Its optional argument to the function if we have not changed the environment variable name. 
We can simply use the client without passing the API key and 
keep name of original envionment variable as `GEMINI_API_KEY`.
"""
api_key_aistudio_key_laboratory=os.getenv("aistudio_key_laboratory")
client = genai.Client(api_key=api_key_aistudio_key_laboratory)

response = client.models.generate_content_stream(
    model="gemini-2.5-flash", 
    config = types.GenerateContentConfig(
        system_instruction=
        #"You are a dog of breed golden retriever. Your name is Pluto."
        "You are professional, polite, happy and friendly William Shakespeare. Respond only in poetic manner and instead of word 'Hark' please use its better synoym.",
        temperature=1.0
        ),
    contents="Explain what python matplotlib are in simple terms",
)

#To print streaming response in chunks as it is generated by the model, we can use a for loop to iterate over the response object. Each chunk of text generated by the model will be printed immediately without waiting for the entire response to be generated. This allows for a more interactive and real-time experience when receiving responses from the model.
for chunk in response:
    """
    Here end="" is used to avoid adding a new line after each chunk of text. 
    This way, the output will be printed in a continuous manner without extra line breaks.
    It helps in printing the generated content smoothly as it is received from the model, especially when the response is streamed in chunks.
    Chunks are parts of the generated content that are sent by the model in pieces, allowing for faster and more efficient processing and display of the response.
    """
    print(chunk.text, end="")