from typing import Dict, List
from src.models import Location, Activity, Restaurant, Hotel

DESTINATIONS: Dict[str, Dict] = {
    "Tokyo": {
        "center": {"lat": 35.6895, "lon": 139.6917},
        "hotels": [
            Hotel(
                id="tokyo_hotel_budget",
                name="Nine Hours Capsule Hotel Shinjuku",
                description="Ultra-modern capsule hotel offering futuristic and minimalist sleeping pods, perfect for solo budget travelers.",
                budget_tier="Budget",
                location=Location(name="Nine Hours Shinjuku", lat=35.6912, lon=139.7021, address="2-19 Shinjuku, Tokyo"),
                rating=4.3,
                price_per_night=45.0
            ),
            Hotel(
                id="tokyo_hotel_mid",
                name="Hotel Gracery Shinjuku",
                description="Famous Godzilla-themed hotel located in the heart of Kabukicho, featuring comfortable rooms and excellent city views.",
                budget_tier="Mid-range",
                location=Location(name="Hotel Gracery Shinjuku", lat=35.6953, lon=139.7019, address="1-19-1 Kabukicho, Shinjuku, Tokyo"),
                rating=4.6,
                price_per_night=165.0
            ),
            Hotel(
                id="tokyo_hotel_luxury",
                name="Park Hyatt Tokyo",
                description="Iconic luxury high-rise hotel offering spacious suites, world-class dining, and panoramic views of Tokyo and Mount Fuji.",
                budget_tier="Luxury",
                location=Location(name="Park Hyatt Tokyo", lat=35.6856, lon=139.6908, address="3-7-1-2 Nishi-Shinjuku, Tokyo"),
                rating=4.9,
                price_per_night=750.0
            )
        ],
        "restaurants": [
            Restaurant(
                id="tokyo_rest_ichiran",
                name="Ichiran Ramen Shinjuku",
                description="Famous tonkotsu (pork bone) ramen served in individual eating booths for a focused culinary experience.",
                cuisine="Japanese Ramen",
                budget_tier="Budget",
                dietary_tags=[],
                location=Location(name="Ichiran Shinjuku", lat=35.6908, lon=139.7008),
                rating=4.5,
                start_hour=10.0,
                end_hour=23.0
            ),
            Restaurant(
                id="tokyo_rest_vegan",
                name="T's Tantan (Tokyo Station)",
                description="Delicious, rich sesame ramen and gyoza made entirely from plant-based ingredients inside Tokyo Station.",
                cuisine="Vegan Japanese",
                budget_tier="Budget",
                dietary_tags=["vegan", "vegetarian"],
                location=Location(name="T's Tantan Tokyo Station", lat=35.6812, lon=139.7671),
                rating=4.7,
                start_hour=10.0,
                end_hour=22.0
            ),
            Restaurant(
                id="tokyo_rest_halal",
                name="Halal Sakura (Ueno)",
                description="Popular cozy spot serving authentic halal-certified Japanese sukiyaki, ramen, and skewers.",
                cuisine="Halal Japanese",
                budget_tier="Mid-range",
                dietary_tags=["halal", "vegetarian"],
                location=Location(name="Halal Sakura Ueno", lat=35.7312, lon=139.7788),
                rating=4.4,
                start_hour=11.3,
                end_hour=21.5
            ),
            Restaurant(
                id="tokyo_rest_tsunahachi",
                name="Tempura Tsunahachi Shinjuku",
                description="Historical tempura parlor frying fresh seafood and seasonal vegetables since 1924.",
                cuisine="Tempura",
                budget_tier="Mid-range",
                dietary_tags=["vegetarian", "gluten-free"],
                location=Location(name="Tempura Tsunahachi", lat=35.6905, lon=139.7032),
                rating=4.6,
                start_hour=11.0,
                end_hour=22.0
            ),
            Restaurant(
                id="tokyo_rest_narisawa",
                name="Narisawa",
                description="Two Michelin-starred restaurant pioneering 'Innovative Satoyama Cuisine', respecting nature on the plate.",
                cuisine="Fine Dining Japanese",
                budget_tier="Luxury",
                dietary_tags=["gluten-free", "vegetarian"],
                location=Location(name="Narisawa Minami Aoyama", lat=35.6685, lon=139.7186),
                rating=4.8,
                start_hour=12.0,
                end_hour=21.0
            )
        ],
        "activities": [
            Activity(
                id="tokyo_act_shibuya",
                name="Shibuya Crossing & Hachiko Statue",
                description="Witness the world's busiest pedestrian scramble, snap photos, and visit the iconic loyal dog statue.",
                cost=0.0,
                categories=["Culture", "Shopping"],
                avg_duration=1.0,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Shibuya Crossing", lat=35.6580, lon=139.7016),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Any",
                rating=4.7
            ),
            Activity(
                id="tokyo_act_sensoji",
                name="Senso-ji Temple (Asakusa)",
                description="Tokyo's oldest and most iconic Buddhist temple, entered through the monumental Kaminarimon (Thunder Gate).",
                cost=0.0,
                categories=["Culture"],
                avg_duration=2.0,
                start_hour=6.0,
                end_hour=17.0,
                location=Location(name="Senso-ji", lat=35.7148, lon=139.7967),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.8
            ),
            Activity(
                id="tokyo_act_meiji",
                name="Meiji Jingu Shrine",
                description="A serene shinto shrine dedicated to Emperor Meiji, nestled within a massive lush forest in the middle of the city.",
                cost=0.0,
                categories=["Culture", "Nature"],
                avg_duration=1.5,
                start_hour=5.0,
                end_hour=18.0,
                location=Location(name="Meiji Shrine", lat=35.6764, lon=139.6993),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.7
            ),
            Activity(
                id="tokyo_act_teamlab",
                name="teamLab Planets TOKYO",
                description="An immersive digital art museum where you walk through water, massive flower projections, and infinity mirror rooms.",
                cost=32.0,
                categories=["Culture", "Relaxation"],
                avg_duration=2.5,
                start_hour=9.0,
                end_hour=22.0,
                location=Location(name="teamLab Planets", lat=35.6436, lon=139.7900),
                physical_intensity="Medium",
                accessibility=False, # Barefoot, water up to knees makes wheelchair access difficult
                weather_suitability="Indoor",
                rating=4.9
            ),
            Activity(
                id="tokyo_act_shinjuku_gyoen",
                name="Shinjuku Gyoen National Garden",
                description="A spacious formal garden blending traditional Japanese, English landscape, and French formal garden styles.",
                cost=5.0,
                categories=["Nature", "Relaxation"],
                avg_duration=2.0,
                start_hour=9.0,
                end_hour=16.5,
                location=Location(name="Shinjuku Gyoen", lat=35.6852, lon=139.7101),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.6
            ),
            Activity(
                id="tokyo_act_akihabara",
                name="Akihabara Electric Town Tour",
                description="Explore the absolute center of Otaku culture, retro video game stores, multi-story electronics shops, and manga stores.",
                cost=0.0,
                categories=["Shopping", "Adventure"],
                avg_duration=3.0,
                start_hour=10.0,
                end_hour=21.0,
                location=Location(name="Akihabara", lat=35.6997, lon=139.7715),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Any",
                rating=4.5
            ),
            Activity(
                id="tokyo_act_skytree",
                name="Tokyo Skytree Observation Deck",
                description="Ascend Japan's tallest tower for breathtaking 360-degree views of the sprawling Tokyo metropolis.",
                cost=25.0,
                categories=["Culture"],
                avg_duration=1.5,
                start_hour=10.0,
                end_hour=21.0,
                location=Location(name="Tokyo Skytree", lat=35.7101, lon=139.8107),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            ),
            Activity(
                id="tokyo_act_tsukiji",
                name="Tsukiji Outer Market Food Tour",
                description="Weave through bustling narrow alleys packed with food stalls selling fresh street seafood, wagyu skewers, and sweet tamago.",
                cost=15.0,
                categories=["Food", "Culture"],
                avg_duration=2.0,
                start_hour=7.0,
                end_hour=14.0,
                location=Location(name="Tsukiji Outer Market", lat=35.6655, lon=139.7707),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Any",
                rating=4.8
            ),
            Activity(
                id="tokyo_act_roppongi_view",
                name="Roppongi Hills Mori Tower Observatory",
                description="Look out at Tokyo Tower and the urban skyline from an spectacular open-air rooftop sky deck or high glass room.",
                cost=20.0,
                categories=["Culture", "Nightlife"],
                avg_duration=1.5,
                start_hour=10.0,
                end_hour=23.0,
                location=Location(name="Roppongi Hills Sky Deck", lat=35.6605, lon=139.7291),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.6
            ),
            Activity(
                id="tokyo_act_takeshita",
                name="Harajuku Takeshita Street",
                description="The epicenter of extreme youth fashion, colorful treats, giant rainbow cotton candy, and quirky animal cafes.",
                cost=0.0,
                categories=["Shopping", "Nightlife"],
                avg_duration=2.0,
                start_hour=10.0,
                end_hour=20.0,
                location=Location(name="Takeshita Street", lat=35.6702, lon=139.7025),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.3
            ),
            # Indoor swap-in alternatives for weather/fatigue
            Activity(
                id="tokyo_act_edo_museum",
                name="Edo-Tokyo Museum (Indoor Alternative)",
                description="Stunning interactive indoor museum showing Tokyo's fascinating history, architecture, and lifestyle from the Edo period.",
                cost=12.0,
                categories=["Culture"],
                avg_duration=2.5,
                start_hour=9.0,
                end_hour=17.5,
                location=Location(name="Edo-Tokyo Museum", lat=35.6963, lon=139.7963),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            ),
            Activity(
                id="tokyo_act_spa_laqua",
                name="Spa LaQua Natural Hot Springs",
                description="A luxurious multi-story indoor thermal spring bathhouse, sauna, and relaxation lounge in the middle of Tokyo.",
                cost=28.0,
                categories=["Relaxation"],
                avg_duration=3.5,
                start_hour=11.0,
                end_hour=23.5,
                location=Location(name="Spa LaQua", lat=35.7067, lon=139.7533),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            )
        ]
    },
    "Paris": {
        "center": {"lat": 48.8566, "lon": 2.3522},
        "hotels": [
            Hotel(
                id="paris_hotel_budget",
                name="Generator Hostel Paris",
                description="Stylish designer hostel in the trendy 10th Arrondissement, offering clean dorms and a scenic rooftop bar with views of Sacré-Cœur.",
                budget_tier="Budget",
                location=Location(name="Generator Hostel", lat=48.8786, lon=2.3694, address="9-11 Place du Colonel Fabien, Paris"),
                rating=4.2,
                price_per_night=55.0
            ),
            Hotel(
                id="paris_hotel_mid",
                name="Hotel Caron de Beaumarchais",
                description="Charming 18th-century boutique hotel in the historic Marais district, loaded with antique clocks, flowered fabrics, and French elegance.",
                budget_tier="Mid-range",
                location=Location(name="Hotel Caron de Beaumarchais", lat=48.8565, lon=2.3582, address="12 Rue Vieille-du-Temple, Paris"),
                rating=4.6,
                price_per_night=190.0
            ),
            Hotel(
                id="paris_hotel_luxury",
                name="The Ritz Paris",
                description="Ultra-prestigious palace hotel on Place Vendôme, representing the height of legendary French refinement, gastronomy, and historic luxury.",
                budget_tier="Luxury",
                location=Location(name="The Ritz Paris", lat=48.8681, lon=2.3294, address="15 Place Vendôme, Paris"),
                rating=4.9,
                price_per_night=1100.0
            )
        ],
        "restaurants": [
            Restaurant(
                id="paris_rest_bouillon",
                name="Bouillon Pigalle",
                description="Large, bustling popular brasserie serving high-quality traditional French bistro fare at unbelievably budget prices.",
                cuisine="French Bistro",
                budget_tier="Budget",
                dietary_tags=["vegetarian"],
                location=Location(name="Bouillon Pigalle", lat=48.8824, lon=2.3378),
                rating=4.5,
                start_hour=11.5,
                end_hour=23.0
            ),
            Restaurant(
                id="paris_rest_vegan",
                name="Le Potager du Marais",
                description="Cozy wooden tavern serving traditional French classics (like Bourguignon and Cassoulet) completely reimagined as vegan.",
                cuisine="Vegan French",
                budget_tier="Mid-range",
                dietary_tags=["vegan", "vegetarian", "gluten-free"],
                location=Location(name="Le Potager du Marais", lat=48.8601, lon=2.3551),
                rating=4.6,
                start_hour=12.0,
                end_hour=22.5
            ),
            Restaurant(
                id="paris_rest_halal",
                name="L'As du Fallafel",
                description="World-renowned Jewish quarter falafel stand serving legendary loaded warm pita pocket sandwiches.",
                cuisine="Middle Eastern",
                budget_tier="Budget",
                dietary_tags=["halal", "vegetarian"],
                location=Location(name="L'As du Fallafel", lat=48.8575, lon=2.3591),
                rating=4.7,
                start_hour=11.0,
                end_hour=23.0
            ),
            Restaurant(
                id="paris_rest_jules_verne",
                name="Le Jules Verne (Eiffel Tower)",
                description="One Michelin-starred gastronomic fine dining located directly on the second floor of the Eiffel Tower, offering views over Paris.",
                cuisine="Modern French Fine Dining",
                budget_tier="Luxury",
                dietary_tags=["gluten-free"],
                location=Location(name="Le Jules Verne", lat=48.8584, lon=2.2945),
                rating=4.7,
                start_hour=12.0,
                end_hour=21.5
            )
        ],
        "activities": [
            Activity(
                id="paris_act_eiffel",
                name="Eiffel Tower Summit Climb",
                description="Behold the iconic iron spire of Paris, take a scenic lift or climb the steps to the summit for magical urban views.",
                cost=28.0,
                categories=["Culture"],
                avg_duration=2.5,
                start_hour=9.0,
                end_hour=23.0,
                location=Location(name="Eiffel Tower", lat=48.8584, lon=2.2945),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.8
            ),
            Activity(
                id="paris_act_louvre",
                name="The Louvre Museum Guided Tour",
                description="Explore the world's largest art museum, home to the Mona Lisa, Winged Victory, and ancient majestic palaces.",
                cost=22.0,
                categories=["Culture"],
                avg_duration=3.5,
                start_hour=9.0,
                end_hour=18.0,
                location=Location(name="Louvre Museum", lat=48.8606, lon=2.3376),
                physical_intensity="High",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.9
            ),
            Activity(
                id="paris_act_orsay",
                name="Musée d'Orsay Art Gallery",
                description="Stunning art museum housed in an ornate former Beaux-Arts railway station, featuring masterpieces of Impressionism.",
                cost=16.0,
                categories=["Culture"],
                avg_duration=2.5,
                start_hour=9.5,
                end_hour=18.0,
                location=Location(name="Musée d'Orsay", lat=48.8599, lon=2.3265),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            ),
            Activity(
                id="paris_act_seine",
                name="Seine River Bateaux Parisiens Cruise",
                description="Relax on a glass-canopied boat cruise along the historic Seine River, passing under ornate historic bridges.",
                cost=15.0,
                categories=["Relaxation", "Nature"],
                avg_duration=1.0,
                start_hour=10.0,
                end_hour=22.0,
                location=Location(name="Seine River Dock", lat=48.8590, lon=2.2931),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Any",
                rating=4.5
            ),
            Activity(
                id="paris_act_montmartre",
                name="Montmartre & Sacré-Cœur Walking Tour",
                description="Wander through cobbled bohemian lanes, see historic artist flats, and climb up to the white-domed Basilica on the hill.",
                cost=0.0,
                categories=["Culture", "Nature"],
                avg_duration=2.5,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Sacré-Cœur Montmartre", lat=48.8867, lon=2.3431),
                physical_intensity="High",
                accessibility=False, # Steep stone steps and heavy cobblestone hills
                weather_suitability="Outdoor",
                rating=4.7
            ),
            Activity(
                id="paris_act_versailles",
                name="Palace & Gardens of Versailles",
                description="A magnificent royal chateau illustrating the absolute scale and gold-gilded excess of Sun King Louis XIV.",
                cost=30.0,
                categories=["Culture", "Nature"],
                avg_duration=4.5,
                start_hour=9.0,
                end_hour=17.5,
                location=Location(name="Palace of Versailles", lat=48.8048, lon=2.1203),
                physical_intensity="High",
                accessibility=True,
                weather_suitability="Any",
                rating=4.8
            ),
            Activity(
                id="paris_act_champs",
                name="Champs-Élysées & Arc de Triomphe",
                description="Walk the grand shopping avenue of Paris and scale the massive triumphal arch built by Napoleon to commemorate victories.",
                cost=13.0,
                categories=["Shopping", "Culture"],
                avg_duration=2.0,
                start_hour=10.0,
                end_hour=23.0,
                location=Location(name="Arc de Triomphe", lat=48.8738, lon=2.2950),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.6
            ),
            Activity(
                id="paris_act_luxembourg",
                name="Luxembourg Gardens Picnic & Relax",
                description="Sit on iconic green metal chairs, watch toy sailboats in the grand pond, and stroll gravel paths lined with status and orange trees.",
                cost=0.0,
                categories=["Relaxation", "Nature"],
                avg_duration=1.5,
                start_hour=7.5,
                end_hour=21.0,
                location=Location(name="Luxembourg Gardens", lat=48.8462, lon=2.3371),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.7
            ),
            # Indoor swap-in alternatives for weather/fatigue
            Activity(
                id="paris_act_orangerie",
                name="Musée de l'Orangerie (Water Lilies)",
                description="Sit in the serene, egg-shaped white rooms designed specifically to display Monet's massive, panoramic Water Lilies series.",
                cost=12.5,
                categories=["Culture", "Relaxation"],
                avg_duration=1.5,
                start_hour=9.0,
                end_hour=18.0,
                location=Location(name="Musée de l'Orangerie", lat=48.8638, lon=2.3226),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            ),
            Activity(
                id="paris_act_opera",
                name="Palais Garnier Opera House Tour",
                description="Walk the breathtaking grand marble staircase, gold foyer, and see Chagall's painted ceiling inside the historic Opera house.",
                cost=14.0,
                categories=["Culture"],
                avg_duration=1.5,
                start_hour=10.0,
                end_hour=17.0,
                location=Location(name="Palais Garnier", lat=48.8719, lon=2.3316),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            )
        ]
    },
    "New York": {
        "center": {"lat": 40.7580, "lon": -73.9855},
        "hotels": [
            Hotel(
                id="ny_hotel_budget",
                name="The Jane Hotel (Greenwich Village)",
                description="Historic riverfront hotel featuring cozy, cabin-style rooms, shared vintage bathrooms, and a hip bohemian ambiance.",
                budget_tier="Budget",
                location=Location(name="The Jane Hotel", lat=40.7383, lon= -74.0098, address="113 Jane St, New York"),
                rating=4.1,
                price_per_night=120.0
            ),
            Hotel(
                id="ny_hotel_mid",
                name="Arlo Nomad",
                description="Charming micro-room boutique hotel in Midtown, featuring custom light walnut furniture and a stunning rooftop terrace near the Empire State.",
                budget_tier="Mid-range",
                location=Location(name="Arlo Nomad", lat=40.7466, lon= -73.9841, address="11 E 31st St, New York"),
                rating=4.5,
                price_per_night=260.0
            ),
            Hotel(
                id="ny_hotel_luxury",
                name="The Plaza Hotel",
                description="World-renowned historic luxury chateau hotel on Fifth Avenue and Central Park South, providing exquisite gold-detailed lodging and butler service.",
                budget_tier="Luxury",
                location=Location(name="The Plaza Hotel", lat=40.7644, lon= -73.9744, address="768 5th Ave, New York"),
                rating=4.8,
                price_per_night=850.0
            )
        ],
        "restaurants": [
            Restaurant(
                id="ny_rest_katz",
                name="Katz's Delicatessen",
                description="Legendary, massive Jewish deli serving piled-high, slow-cured pastrami and corned beef sandwiches since 1888.",
                cuisine="Jewish Deli",
                budget_tier="Mid-range",
                dietary_tags=["halal"],
                location=Location(name="Katz's Deli", lat=40.7222, lon= -73.9874),
                rating=4.6,
                start_hour=8.0,
                end_hour=23.0
            ),
            Restaurant(
                id="ny_rest_vegan",
                name="Dirt Candy (Lower East Side)",
                description="Award-winning Michelin-starred vegetarian restaurant where vegetables are treated as culinary stars in creative tasting menus.",
                cuisine="Fine Vegetarian",
                budget_tier="Luxury",
                dietary_tags=["vegetarian", "vegan", "gluten-free"],
                location=Location(name="Dirt Candy", lat=40.7196, lon= -73.9897),
                rating=4.7,
                start_hour=17.5,
                end_hour=23.0
            ),
            Restaurant(
                id="ny_rest_halal",
                name="The Halal Guys (53rd & 6th)",
                description="World-famous food cart pioneering seasoned gyro meat, chicken, rice platters, and their legendary fiery red and creamy white sauces.",
                cuisine="Halal Street Food",
                budget_tier="Budget",
                dietary_tags=["halal"],
                location=Location(name="The Halal Guys", lat=40.7618, lon= -73.9793),
                rating=4.4,
                start_hour=10.0,
                end_hour=24.0
            ),
            Restaurant(
                id="ny_rest_joe_pizza",
                name="Joe's Pizza (Greenwich Village)",
                description="The ultimate quintessential NY street slice joint. No frills, fresh, hot, and highly praised by celebrities and locals.",
                cuisine="Pizza Slice",
                budget_tier="Budget",
                dietary_tags=["vegetarian"],
                location=Location(name="Joe's Pizza", lat=40.7306, lon= -74.0008),
                rating=4.7,
                start_hour=10.0,
                end_hour=24.0
            )
        ],
        "activities": [
            Activity(
                id="ny_act_times_square",
                name="Times Square Neon Wander",
                description="Soak in the glowing billboard lights, street performers, and electrical pulse of the absolute theater district crossroads.",
                cost=0.0,
                categories=["Culture", "Shopping", "Nightlife"],
                avg_duration=1.0,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Times Square", lat=40.7580, lon= -73.9855),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Any",
                rating=4.4
            ),
            Activity(
                id="ny_act_central_park",
                name="Central Park Bicycle & Walk",
                description="Explore 843 acres of green lawns, stone bridges, rowboat lakes, and beautiful walkways in the heart of Manhattan.",
                cost=12.0,
                categories=["Nature", "Relaxation"],
                avg_duration=2.5,
                start_hour=6.0,
                end_hour=20.0,
                location=Location(name="Central Park Bow Bridge", lat=40.7758, lon= -73.9716),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.8
            ),
            Activity(
                id="ny_act_met",
                name="Metropolitan Museum of Art (The Met)",
                description="One of the world's absolute premier art institutions, presenting 5,000 years of masterpieces, including Egyptian temples.",
                cost=30.0,
                categories=["Culture"],
                avg_duration=3.5,
                start_hour=10.0,
                end_hour=17.0,
                location=Location(name="The Met", lat=40.7794, lon= -73.9632),
                physical_intensity="High",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.9
            ),
            Activity(
                id="ny_act_statue",
                name="Statue of Liberty & Ellis Island Ferry",
                description="Board the ferry to Liberty Island to see the copper monument of freedom up close, and research immigrant records on Ellis Island.",
                cost=25.5,
                categories=["Culture"],
                avg_duration=3.5,
                start_hour=9.0,
                end_hour=15.5,
                location=Location(name="Battery Park Ferry Dock", lat=40.7032, lon= -74.0170),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.7
            ),
            Activity(
                id="ny_act_highline",
                name="The High Line Elevated Park Walk",
                description="Walk down a stunning public park built on a historic elevated freight rail line, elevated above Manhattan's West Side streets.",
                cost=0.0,
                categories=["Nature", "Relaxation"],
                avg_duration=1.5,
                start_hour=7.0,
                end_hour=22.0,
                location=Location(name="The High Line", lat=40.7480, lon= -74.0048),
                physical_intensity="Medium",
                accessibility=True, # Elevator access points available at major cross streets
                weather_suitability="Outdoor",
                rating=4.7
            ),
            Activity(
                id="ny_act_empire_state",
                name="Empire State Building Observation Deck",
                description="Ascend to the open-air 86th-floor observatory of New York's ultimate landmark skyscraper.",
                cost=44.0,
                categories=["Culture"],
                avg_duration=1.5,
                start_hour=10.0,
                end_hour=23.0,
                location=Location(name="Empire State Building", lat=40.7484, lon= -73.9857),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            ),
            Activity(
                id="ny_act_chelsea_market",
                name="Chelsea Market & Shopping Tour",
                description="Shop in a former Oreo factory, now a bustling indoor food court, market, and home to trendy local boutiques.",
                cost=0.0,
                categories=["Shopping", "Food"],
                avg_duration=2.0,
                start_hour=8.0,
                end_hour=21.0,
                location=Location(name="Chelsea Market", lat=40.7420, lon= -74.0062),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.6
            ),
            # Indoor swap-in alternatives for weather/fatigue
            Activity(
                id="ny_act_moma",
                name="Museum of Modern Art (MoMA)",
                description="Explore world-leading modern and contemporary art works including Van Gogh's Starry Night and Warhol's Soup Cans.",
                cost=28.0,
                categories=["Culture"],
                avg_duration=2.5,
                start_hour=10.5,
                end_hour=17.5,
                location=Location(name="MoMA", lat=40.7614, lon= -73.9776),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            ),
            Activity(
                id="ny_act_sojo_spa",
                name="SoJo Spa Club (Indoor Relaxation Alternative)",
                description="A luxurious multi-story indoor/outdoor bathhouse and spa facility with stunning Manhattan skyline pool views across the Hudson.",
                cost=75.0,
                categories=["Relaxation"],
                avg_duration=4.0,
                start_hour=9.0,
                end_hour=21.0,
                location=Location(name="SoJo Spa", lat=40.8033, lon= -73.9912),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            )
        ]
    },
    "Rome": {
        "center": {"lat": 41.8902, "lon": 12.4922},
        "hotels": [
            Hotel(
                id="rome_hotel_budget",
                name="The Beehive",
                description="Cozy, eco-conscious budget hostel and guest house located near Termini Station, offering a lush organic garden cafe.",
                budget_tier="Budget",
                location=Location(name="The Beehive", lat=41.9025, lon=12.5029, address="Via Marghera 8, Rome"),
                rating=4.4,
                price_per_night=60.0
            ),
            Hotel(
                id="rome_hotel_mid",
                name="Hotel Santa Maria (Trastevere)",
                description="Charming mid-scale hotel set in a converted 16th-century convent, boasting an orange-tree courtyard in trendy Trastevere.",
                budget_tier="Mid-range",
                location=Location(name="Hotel Santa Maria", lat=41.8893, lon=12.4695, address="Vicolo del Piede 2, Rome"),
                rating=4.7,
                price_per_night=180.0
            ),
            Hotel(
                id="rome_hotel_luxury",
                name="Hotel de Russie",
                description="Superlative luxury hotel between the Spanish Steps and Piazza del Popolo, featuring gorgeous terraced secret gardens.",
                budget_tier="Luxury",
                location=Location(name="Hotel de Russie", lat=41.9103, lon=12.4764, address="Via del Babuino 9, Rome"),
                rating=4.9,
                price_per_night=850.0
            )
        ],
        "restaurants": [
            Restaurant(
                id="rome_rest_da_enzo",
                name="Da Enzo al 29",
                description="A tiny, incredibly popular Trastevere trattoria renowned for serving Rome's best Carbonara and Cacio e Pepe.",
                cuisine="Roman Trattoria",
                budget_tier="Budget",
                dietary_tags=["vegetarian"],
                location=Location(name="Da Enzo al 29", lat=41.8885, lon=12.4786),
                rating=4.6,
                start_hour=12.3,
                end_hour=23.0
            ),
            Restaurant(
                id="rome_rest_vegan_roma",
                name="Buddy Veggy Restaurant",
                description="Vibrant modern restaurant in the city center serving vegan and vegetarian pizzas, pasta, and rich tiramisu.",
                cuisine="Vegetarian Italian",
                budget_tier="Mid-range",
                dietary_tags=["vegan", "vegetarian", "gluten-free"],
                location=Location(name="Buddy Veggy", lat=41.8973, lon=12.4765),
                rating=4.5,
                start_hour=11.0,
                end_hour=23.0
            ),
            Restaurant(
                id="rome_rest_halal",
                name="Kebab Station & Halal Indian Food",
                description="Generous portions of halal meat wraps, curries, and vegetarian options located close to Termini.",
                cuisine="Halal & Indian",
                budget_tier="Budget",
                dietary_tags=["halal", "vegetarian"],
                location=Location(name="Kebab Station Termini", lat=41.9015, lon=12.5005),
                rating=4.1,
                start_hour=10.5,
                end_hour=22.5
            ),
            Restaurant(
                id="rome_rest_la_pergola",
                name="La Pergola",
                description="Rome's only three Michelin-starred restaurant, offering spectacular fine dining overlooking the Vatican.",
                cuisine="Fine Italian Gastronomy",
                budget_tier="Luxury",
                dietary_tags=["gluten-free", "vegetarian"],
                location=Location(name="La Pergola Rome", lat=41.9192, lon=12.4452),
                rating=4.9,
                start_hour=19.0,
                end_hour=23.5
            )
        ],
        "activities": [
            Activity(
                id="rome_act_colosseum",
                name="Colosseum & Roman Forum Tour",
                description="Step onto the stone arena floors of Rome's ancient architectural wonder, followed by walking through the Senate ruins.",
                cost=22.0,
                categories=["Culture"],
                avg_duration=3.0,
                start_hour=8.5,
                end_hour=19.0,
                location=Location(name="Colosseum", lat=41.8902, lon=12.4922),
                physical_intensity="High",
                accessibility=True, # Elevators installed for standard viewing levels
                weather_suitability="Outdoor",
                rating=4.9
            ),
            Activity(
                id="rome_act_vatican",
                name="Vatican Museums & Sistine Chapel",
                description="Behold Michelangelo's ceiling frescoes, massive marble statuary, and Raphael's rooms in the papal palace complex.",
                cost=25.0,
                categories=["Culture"],
                avg_duration=3.5,
                start_hour=9.0,
                end_hour=18.0,
                location=Location(name="Vatican Museum Entrance", lat=41.9068, lon=12.4534),
                physical_intensity="High",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            ),
            Activity(
                id="rome_act_trevi",
                name="Trevi Fountain Coin Toss",
                description="Toss a coin into the roaring baroque water monument to guarantee you will return to Rome.",
                cost=0.0,
                categories=["Culture", "Relaxation"],
                avg_duration=1.0,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Trevi Fountain", lat=41.9009, lon=12.4833),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.8
            ),
            Activity(
                id="rome_act_pantheon",
                name="The Pantheon Visit",
                description="Behold the world's largest unreinforced concrete dome, built 2,000 years ago, complete with its open oculus sky window.",
                cost=5.0,
                categories=["Culture"],
                avg_duration=1.0,
                start_hour=9.0,
                end_hour=19.0,
                location=Location(name="The Pantheon", lat=41.8986, lon=12.4769),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor", # Oculus lets rain in, but still is classified as indoor structure
                rating=4.8
            ),
            Activity(
                id="rome_act_navona",
                name="Piazza Navona Street Artists",
                description="Wander Rome's most colorful and spacious plaza, boasting Bernini's central Fountain of the Four Rivers.",
                cost=0.0,
                categories=["Relaxation", "Culture"],
                avg_duration=1.5,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Piazza Navona", lat=41.8988, lon=12.4731),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.7
            ),
            Activity(
                id="rome_act_borghese",
                name="Villa Borghese Gardens Walk & Museum",
                description="Stroll the beautiful park pathways and view exquisite marble statues by Bernini inside the Galleria Borghese.",
                cost=15.0,
                categories=["Nature", "Culture"],
                avg_duration=2.5,
                start_hour=9.0,
                end_hour=19.0,
                location=Location(name="Galleria Borghese", lat=41.9142, lon=12.4921),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Any",
                rating=4.8
            ),
            Activity(
                id="rome_act_spanish_steps",
                name="Spanish Steps Climb",
                description="Scale the beautiful historic staircase leading up from Piazza di Spagna, perfect for sitting and scenic viewing.",
                cost=0.0,
                categories=["Culture", "Relaxation"],
                avg_duration=1.0,
                start_hour=0.0,
                end_hour=24.0,
                location=Location(name="Spanish Steps", lat=41.9059, lon=12.4827),
                physical_intensity="Medium",
                accessibility=False, # Steep stone historical staircase, difficult for wheelchair users
                weather_suitability="Outdoor",
                rating=4.6
            ),
            # Indoor swap-in alternatives for weather/fatigue
            Activity(
                id="rome_act_capitol_museum",
                name="Capitoline Museums",
                description="The world's oldest public museum complex, home to the iconic bronze Lupa Capitolina (She-Wolf) and ancient statues.",
                cost=16.0,
                categories=["Culture"],
                avg_duration=2.0,
                start_hour=9.3,
                end_hour=19.5,
                location=Location(name="Capitoline Museums", lat=41.8929, lon=12.4825),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            )
        ]
    },
    "Reykjavik": {
        "center": {"lat": 64.1466, "lon": -21.9426},
        "hotels": [
            Hotel(
                id="reyk_hotel_budget",
                name="Kex Hostel",
                description="Trendy, industrial-chic social hostel in a former biscuit factory, showcasing vintage decor and a buzzing gastropub.",
                budget_tier="Budget",
                location=Location(name="Kex Hostel", lat=64.1460, lon= -21.9213, address="Skúlagata 28, Reykjavik"),
                rating=4.4,
                price_per_night=80.0
            ),
            Hotel(
                id="reyk_hotel_mid",
                name="Apotek Hotel",
                description="Stylish boutique hotel housed in a landmark historical pharmacy building in the absolute center of downtown Reykjavik.",
                budget_tier="Mid-range",
                location=Location(name="Apotek Hotel", lat=64.1472, lon= -21.9392, address="Austurstræti 16, Reykjavik"),
                rating=4.6,
                price_per_night=230.0
            ),
            Hotel(
                id="reyk_hotel_luxury",
                name="The Retreat at Blue Lagoon",
                description="Sublime luxury sanctuary built into volcanic moss-covered lava fields, boasting private direct entry into thermal waters.",
                budget_tier="Luxury",
                location=Location(name="The Retreat at Blue Lagoon", lat=63.8804, lon= -22.4531, address="Nordurljosavegur 7, Grindavik"),
                rating=4.9,
                price_per_night=900.0
            )
        ],
        "restaurants": [
            Restaurant(
                id="reyk_rest_hotdog",
                name="Bæjarins Beztu Pylsur",
                description="Legendary downtown street food kiosk serving Iceland's iconic lamb-based hot dogs 'with everything'.",
                cuisine="Icelandic Hot Dogs",
                budget_tier="Budget",
                dietary_tags=[],
                location=Location(name="Bæjarins Beztu Kiosk", lat=64.1483, lon= -21.9376),
                rating=4.6,
                start_hour=10.0,
                end_hour=24.0
            ),
            Restaurant(
                id="reyk_rest_glama",
                name="Gló Restaurant",
                description="Cozy, modern health-focused cafe serving fresh plant-based macro bowls, raw lasagnas, and vegetarian soups.",
                cuisine="Healthy Organic",
                budget_tier="Budget",
                dietary_tags=["vegan", "vegetarian", "gluten-free"],
                location=Location(name="Gló Restaurant", lat=64.1459, lon= -21.9287),
                rating=4.4,
                start_hour=11.0,
                end_hour=21.0
            ),
            Restaurant(
                id="reyk_rest_shalimar",
                name="Shalimar Pakistani Curry",
                description="Cozy northernmost Pakistani restaurant, serving robust curries, hot tandoori naan, and halal meats.",
                cuisine="Pakistani & Indian",
                budget_tier="Mid-range",
                dietary_tags=["halal", "vegetarian"],
                location=Location(name="Shalimar Pakistani", lat=64.1470, lon= -21.9388),
                rating=4.3,
                start_hour=11.5,
                end_hour=22.0
            ),
            Restaurant(
                id="reyk_rest_grillmarket",
                name="Grillmarkaðurinn (Grillmarket)",
                description="Fine dining restaurant cooking local arctic ingredients (lamb, cod, duck) over glowing coal fire grills in a volcanic-stone interior.",
                cuisine="Icelandic Fine Dining",
                budget_tier="Luxury",
                dietary_tags=["gluten-free"],
                location=Location(name="Grillmarkaðurinn", lat=64.1467, lon= -21.9384),
                rating=4.7,
                start_hour=18.0,
                end_hour=23.0
            )
        ],
        "activities": [
            Activity(
                id="reyk_act_blue_lagoon",
                name="Blue Lagoon Geothermal Bathing",
                description="Soak in milky-blue, silica-rich mineral waters heated by geothermal steam in the middle of a massive volcanic black lava field.",
                cost=75.0,
                categories=["Relaxation", "Nature"],
                avg_duration=3.5,
                start_hour=8.0,
                end_hour=21.0,
                location=Location(name="Blue Lagoon", lat=63.8804, lon= -22.4531),
                physical_intensity="Low",
                accessibility=True, # Provides special aquatic wheelchairs and ramp entries
                weather_suitability="Any", # Heated natural thermal waters make it glorious even in pouring rain or snow
                rating=4.8
            ),
            Activity(
                id="reyk_act_hallgrimskirkja",
                name="Hallgrímskirkja Cathedral & Tower",
                description="Admire the concrete basalt-organ pipe architecture of Iceland's tallest church, and ride the lift to the top tower for city views.",
                cost=10.0,
                categories=["Culture"],
                avg_duration=1.0,
                start_hour=9.0,
                end_hour=20.0,
                location=Location(name="Hallgrímskirkja", lat=64.1417, lon= -21.9266),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            ),
            Activity(
                id="reyk_act_harpa",
                name="Harpa Concert Hall Tour",
                description="Explore the award-winning waterfront concert hall featuring a striking multi-colored geometric glass facade inspired by basalt rocks.",
                cost=0.0,
                categories=["Culture", "Shopping"],
                avg_duration=1.5,
                start_hour=10.0,
                end_hour=18.0,
                location=Location(name="Harpa Concert Hall", lat=64.1504, lon= -21.9326),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            ),
            Activity(
                id="reyk_act_golden_circle",
                name="Golden Circle Day Tour",
                description="Visit Thingvellir National Park rift valley, the powerful Strokkur Geysir eruptions, and the roaring Gullfoss double-cascade waterfall.",
                cost=55.0,
                categories=["Nature", "Adventure"],
                avg_duration=8.0,
                start_hour=8.0,
                end_hour=16.0,
                location=Location(name="Gullfoss Waterfall", lat=64.3271, lon= -20.1199),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Outdoor",
                rating=4.9
            ),
            Activity(
                id="reyk_act_laugarvegur",
                name="Laugavegur Shopping & Cafes",
                description="Walk Reykjavik's main pedestrian street lined with designer outerwear shops, cozy bookstores, and craft bakeries.",
                cost=0.0,
                categories=["Shopping", "Relaxation"],
                avg_duration=2.0,
                start_hour=10.0,
                end_hour=19.0,
                location=Location(name="Laugavegur Street", lat=64.1450, lon= -21.9248),
                physical_intensity="Medium",
                accessibility=True,
                weather_suitability="Any",
                rating=4.4
            ),
            # Indoor swap-in alternatives for weather/fatigue
            Activity(
                id="reyk_act_perlan",
                name="Perlan Museum Wonders of Iceland",
                description="Experience a real indoor ice cave, stand on a revolving deck, and watch a digital Aurora show inside a stunning glass-domed museum.",
                cost=35.0,
                categories=["Culture", "Nature"],
                avg_duration=2.5,
                start_hour=9.0,
                end_hour=21.0,
                location=Location(name="Perlan", lat=64.1292, lon= -21.9189),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.7
            ),
            Activity(
                id="reyk_act_flyover",
                name="FlyOver Iceland Flight Ride",
                description="Strap into a motion seat and soar over grand glaciers, canyons, and remote volcanic plains on a massive spherical screen inside.",
                cost=38.0,
                categories=["Adventure"],
                avg_duration=1.0,
                start_hour=11.0,
                end_hour=19.0,
                location=Location(name="FlyOver Grandi", lat=64.1541, lon= -21.9535),
                physical_intensity="Low",
                accessibility=True,
                weather_suitability="Indoor",
                rating=4.8
            )
        ]
    }
}
